### ISSUE TITLE
issues with downloading passband files from the website

### ISSUE THREAD

**Issue by gecheline** [phoebe-project/tables.phoebe-project.org#1]
When manually downloading .fits passbands from phoebe-project.org, unpacking the resulting tar file (on a Mac) gives me the following error:
`
tar -xvf tmpyqO4R7.tar
x johnson_i.fits
x johnson_v.fits: Truncated tar archive
tar: Error exit delayed from previous errors.`
This manages to expand the fits files but using them with Phoebe then throws a keyword error on 'PTFORDER'.

From the file manager, double clicking on the tar archive itself (which should handle the extracting automatically) also returns an error (Error 1 - No such process.)

None of these issues are present if I instead download the passbands with `phoebe.download_passband()`

**Comment by aprsa** [comment]
New passbands fix this issue.
